export { default as Choose } from './Choose'
export { default as Furniture } from './Furniture'
export { default as Hero } from './Hero'
export { default as Newsletter } from './Newsletter'
export { default as Partner } from './Partner'
export { default as Product } from './Product'